# workflow name
name: Hexo x Github Pages CI

# master push時に発火
on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  changeName:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: change directory name & return for git
      run: |
        git config user.name "j-ushikoshi"
        git config user.email "j-ushikoshi@nec.com"
        git remote set-url origin https://:${{ secrets.GITHUB_PASS }}@github.com/j-xaas/j-xaas.github.io
        git mv j-blog _j-blog
        git add *
        git commit -m "Change directory name!"
        git push origin master

    # git checkout master 今回は不要
    # 以下は不要？　Settingに規定したgitのパスワードを読み込むくだり
    # git remote set-url origin https://:${{ secrets.GITHUB_PASS }}@github.com/j-xaas/j-xaas.github.io

  # ただのmvではだとj-blogと_j-blogが両方できてしまう...
  # git mvにしてみる？

    # Runs a set of commands using the runners shell
