# workflow name
name: Hexo x Github Pages CI

# master push時に発火
on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  changeName:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Change hexo directory name
      run: mv j-blog _j-blog
    - name: return for git
      run: |
        git add *
        git commit -m "Change directory name"
        git push origin master


    # Runs a set of commands using the runners shell
